version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: ./api-server-django/.env
    build:
      context: .
      dockerfile: ./service/Django.Dockerfile
    networks:
      - db_network
      - web_network
    volumes:
      - ./api-server-django:/usr/src/app
  appseed-app-nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5000:5000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
  react-ui:
    container_name: react-soft-ui
    build:
      context: .
      dockerfile: ./service/React.Dockerfile
    volumes:
      - './react-ui:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    networks:
      - web_network
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
